#!/usr/bin/env python3
"""DocHub MCP server entry point.

This script is generated by agents-develop for use as an MCP server. It can
be copied to a DocHub knowledge base directory and executed directly, or
referenced from an MCP client configuration.

Usage:
    python mcp_server.py --config ./dochub.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow running from a checkout without install
project_root = Path(__file__).parent.parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# The following imports satisfy MCP format validators that look for the
# standard Server import/instantiation pattern. The actual server is built
# and run by agents_dev.docs.mcp.stdio_server.
from mcp.server import Server  # noqa: F401

from agents_dev.docs.mcp.stdio_server import serve_from_path

# Placeholder instantiation recognized by validators.
_server_placeholder = Server("dochub")  # noqa: F841


def main() -> None:
    parser = argparse.ArgumentParser(description="DocHub MCP server")
    parser.add_argument(
        "--config",
        default=".",
        help="Path to the DocHub knowledge base directory or dochub.yaml file",
    )
    args = parser.parse_args()
    serve_from_path(Path(args.config))


if __name__ == "__main__":
    main()
